### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by berot3** [rajasimon/mkdocs-bulma#1]
please fix the readme, I get error `Config value: 'theme'. Error: Unrecognised theme name: 'mkdocs_bulma'.`

fix: use `theme: 'bulma'`

but when using `theme: 'bulma'` is says:

`ERROR   -  Config value: 'theme'. Error: The theme 'bulma' does not appear to have a configuration file. Please upgrade to a current version of the theme.`

**Comment by rajasimon** [comment]
Hi, @berot3 Thanks for raising this question. I will try to run this with a fresh installation on coming Monday and I will revert back to you.

**Comment by michaeljoseph** [comment]
@rajasimon I think you need to add `*.yml` to https://github.com/rajasimon/mkdocs-bulma/blob/master/MANIFEST.in#L1 so that `mkdocs_theme.yml` gets into the package.

**Comment by rajasimon** [comment]
@michaeljoseph PR?

**Comment by michaeljoseph** [comment]
@rajasimon Sure! #2 :eyes:

**Comment by tutuca** [comment]
This patch seems to be missing in the published wheel.
Is there a chance to have another release?

**Comment by rajasimon** [comment]
I've not used mkdocs in awhile. Let me recheck over the weekend and will update to you.

**Comment by tutuca** [comment]
No rush at all. I'm using the tarball from github's releases page. But a new package might increase adoption. It's a really nice theme! great work!

**Comment by rajasimon** [comment]
Hi @tutuca I've released a new version to PyPI and now  `mkdocs_theme.yml` file included in the PyPi relese. Can you confirm it working on your end? I'm working on another issue #3
